envectorflat:
  uri: localhost:50050
  eval_mode: mm
  case_type: PerformanceCustomDataset
  db_label: PUBMED768D400K-FLAT
  custom_case_name: PUBMED768D400K
  custom_case_description: PUBMED768D400K benchmark (768D, 400K vectors)
  custom_dataset_name: PUBMED768D400K
  custom_dataset_dir: /data/vectordb_bench/dataset/PUBMED768D400K
  custom_dataset_size: 400335
  custom_dataset_dim: 768
  custom_dataset_metric_type: COSINE
  custom_dataset_file_count: 1
  custom_dataset_use_shuffled: false
  custom_dataset_with_gt: true
  k: 10
  drop_old: true
  load: true

envectorivfflat:
  uri: localhost:50050
  eval_mode: mm
  case_type: PerformanceCustomDataset
  db_label: PUBMED768D400K-IVF
  custom_case_name: PUBMED768D400K
  custom_case_description: PUBMED768D400K benchmark (768D, 400K vectors)
  custom_dataset_name: PUBMED768D400K
  custom_dataset_dir: /data/vectordb_bench/dataset/PUBMED768D400K
  custom_dataset_size: 400335
  custom_dataset_dim: 768
  custom_dataset_metric_type: COSINE
  custom_dataset_file_count: 1
  custom_dataset_use_shuffled: false
  custom_dataset_with_gt: true
  k: 10
  nlist: 32768
  nprobe: 6
  train_centroids: true
  is_vct: true
  centroids_path: /data/centroids/centroids.npy
  vct_path: /data/centroids/tree_info.pkl
  drop_old: true
  load: true
  